# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-bananapi-f3.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-milkv-jupiter.dtb
dtb-$(CONFIG_SOC_SPACEMIT_K1) += k1-orangepi-rv2.dtb

dtb-$(CONFIG_SOC_SPACEMIT_K2) += k2_fpga_1x1.dtb

