# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SPACEMIT_K3_CAM_IMX219) += imx219_sensor.o
obj-$(CONFIG_SPACEMIT_K3_CAM_IMX415) += imx415_sensor.o
obj-$(CONFIG_SPACEMIT_K3_CAM_OV5647) += ov5647_sensor.o