# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_EC_K3_GMAC) += ec_stmmac.o

ec_stmmac-objs := stmmac_main-ethercat.o \
                  stmmac_ethtool-ethercat.o \
                  stmmac_mdio-ethercat.o \
                  ring_mode-ethercat.o \
                  chain_mode-ethercat.o \
                  dwmac_lib-ethercat.o \
                  dwmac1000_core-ethercat.o \
                  dwmac1000_dma-ethercat.o \
                  dwmac100_core-ethercat.o \
                  dwmac100_dma-ethercat.o \
                  enh_desc-ethercat.o \
                  norm_desc-ethercat.o \
                  mmc_core-ethercat.o \
                  stmmac_hwtstamp-ethercat.o \
                  stmmac_ptp-ethercat.o \
                  dwmac4_descs-ethercat.o \
                  dwmac4_dma-ethercat.o \
                  dwmac4_lib-ethercat.o \
                  dwmac4_core-ethercat.o \
                  dwmac5-ethercat.o \
                  hwif-ethercat.o \
                  stmmac_tc-ethercat.o \
                  dwxgmac2_core-ethercat.o \
                  dwxgmac2_dma-ethercat.o \
                  dwxgmac2_descs-ethercat.o \
                  stmmac_xdp-ethercat.o \
                  stmmac_est-ethercat.o \
                  stmmac_fpe-ethercat.o \
                  stmmac_vlan-ethercat.o \
                  stmmac_platform-ethercat.o \
                  dwmac-spacemit-ethqos-ethercat.o
