/* SPDX-License-Identifier: GPL-2.0 */

#ifndef __DT_BINDINGS_PMU_K3_H__
#define __DT_BINDINGS_PMU_K3_H__

#define K3_PMU_BUS_PWR_DOMAIN	0
#define K3_PMU_VPU_PWR_DOMAIN	1
#define K3_PMU_GPU_PWR_DOMAIN	2
#define K3_PMU_LCD_PWR_DOMAIN	3
#define K3_PMU_ISP_PWR_DOMAIN	4
#define K3_PMU_AUD_PWR_DOMAIN	5
#define K3_PMU_GNSS_PWR_DOMAIN	6
#define K3_PMU_HDMI_PWR_DOMAIN	7
#define K3_PMU_DUMMY_PWR_DOMAIN	8

#endif
