# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Spacemit SOC specific device drivers.
#
obj-$(CONFIG_SPACEMIT_HMP) +=	hmp.o
obj-$(CONFIG_SPACEMIT_PM_DOMAINS) += pm_domain/
obj-$(CONFIG_SPACEMIT_V2D) += v2d/
obj-$(CONFIG_SPACEMIT_DDR_QOS) += ddr_qos.o
obj-$(CONFIG_SPACEMIT_REBOOT_CONTROL) += spacemit_reboot.o
