# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Spacemit SOC specific device drivers.
#
obj-$(CONFIG_SPACEMIT_HMP) +=	hmp.o
obj-$(CONFIG_SPACEMIT_PM_DOMAINS) += pm_domain/
obj-$(CONFIG_SPACEMIT_V2D) += v2d/
obj-$(CONFIG_SPACEMIT_REBOOT_CONTROL) += spacemit_reboot.o
obj-$(CONFIG_SPACEMIT_SOCINFO) += spacemit-socinfo.o
obj-$(CONFIG_SPACEMIT_SUSPEND_AFFINITY) += suspend/
obj-$(CONFIG_SPACEMIT_POWERKEY_MONITOR) += pwrkey_monitor.o
